server:
  port: 8080

spring:
  #批处理配置
  batch:
    #数据库初始化配置
    initialize-schema: always
    #指定启动的父任务，子任务只能随父任务启动而启动
#    job:
#      names: parentJob
  #对外暴露的名字
  application:
    name: springboot-batch
  #设置数据源
  datasource:
    url: jdbc:mysql://localhost:3319/springboot_batch_test01?serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    druid:
      # 最小数
      min-idle: 5
      # 最大数
      max-active: 20
      # 初始大小
      initial-size: 5
      # 配置获取连接等待超时时间
      max-wait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间  单位为毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat,wall
    #batch信息持久化的构建数据库的默认sql语句
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql